[default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
remappings = ["forgeg-std/=lib/forge-std/src", "@openzeppelin/=lib/openzeppelin-contracts/"]
# solc = "0.8.11"
auto_detect_solc = true
optimizer = true
optimizer_runs = 500
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config